### ISSUE TITLE
BettiMatching for 3D volumes

### ISSUE THREAD

**Issue by Saumya-Gupta-26** [nstucki/Betti-matching#2]
Hello, thank you for this fantastic work! I was trying to use BettiMatching as a topological metric to evaluate some 3D volumes and ran into an error at the following line:

https://github.com/nstucki/Betti-matching/blob/d68e1718a7b35a8edd420c6351a973d25d97e4fc/BettiMatching.py#L197

It seems the code requires the images to be 2D. Is my understanding correct? I wanted to confirm because the documentation says it takes as input an Image (numpy array / torch tensor) but does not mention any restriction on the dimension.

Thanks!

**Comment by nstucki** [comment]
Hello, yes that is correct. I am sorry for not pointing this out enough: the current version only works for 2D images, simply because the python implementation is too slow for 3D images. 

I am working on an implementation in C++ right now, which will compute the Betti Matching for images of any dimension. It will be uploaded to this git as soon as possible.

Best regards!
